### ISSUE TITLE
Chrome 62 on Windows bug: TypeError: Cannot read property 'vertices' of undefined

### ISSUE THREAD

**Issue by mbsimonovic** [3dmol/3Dmol.js#352]
This happens only in Chrome 62 on Windows 8&10 (Chrome 61&62 on MacOS work just fine, Chrome 43, 60, 61 on Windows also works fine). 

The offending line is:
```
                if(balls.vertices == 0) balls = null; //no balls
```

and it's caused when I try to show hetero atoms using this filter:

```
        viewer.addStyle({and:[{hetflag:true},{not:{resn:'HOH'}}]},{stick:{opacity:0.65}});
```

<img width="965" alt="screen shot 2017-11-06 at 09 35 37" src="https://user-images.githubusercontent.com/888008/32432315-6ae75386-c2d7-11e7-9aa6-dd878a8e7d27.png">

Here's the full html snippet to reproduce the bug:

[chrome62-windows-bug.zip](https://github.com/3dmol/3Dmol.js/files/1445536/chrome62-windows-bug.zip)

**Comment by dkoes** [comment]
I just pushed a fix, although I have no idea why this would be unique to windows.  Can you let me know if it looks okay?

**Comment by mbsimonovic** [comment]
`stickGeometry.sphereGeometry` on line 20885 is undefined, that's why it fails afterwards, and tracing the code upstream, `options.supportsImposters` is false on line 20756, and options.supportsAIA is true, which means `stickGeometry` is initialized with:

```
stickGeometry = new $3Dmol.Geometry(true); //don't actually have instanced sticks
```

which leaves stickGeometry.sphereGeometry uninitialized, and it fails afterwards.

**Comment by mbsimonovic** [comment]
btw this doesnt fix it because balls is undefined, so balls.vertices will again throw a TypeError.

```
                if((balls && (balls.vertices === 'undefined' || balls.vertices == 0) balls = null; //no balls
```
but this would fix it:
```
                if(!balls || typeof(balls.vertices) === 'undefined' || balls.vertices == 0) balls = null; //no balls
```

What makes this weird is that `options.supportsImposters` is true on Chrome 61?!

**Comment by dkoes** [comment]
Sorry, I didn't read the error message carefully enough.
